#!/bin/bash
export old="$(pwd)"

cd ..
git clone https://github.com/thenameisluk/mdplop mp #conflict with executable
cd mp
mkdir build
cd build
cmake ..
make -j$(nproc)
mv -v mdplop ../..
cd ../..

echo ./mdplop "$old" ./build
./mdplop "$old" ./build

mv -v ./build "$old"/build